apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  namespace: {{ DEPLOY_TO }}
  labels:
    component: elasticsearch
    role: data
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    component: elasticsearch
    role: data
