apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
  labels:
    component: elasticsearch
    role: client
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    nodePort: 30004
    protocol: TCP
