language: node_js

python:
- '2.7'
node_js:
- '7.2.1'

install:
- pip install -r requirements.txt --user
- cd ui/
- npm install

before_script:
- export PYTHONPATH=.:./deploy/mac_osx/xbrowse_settings:$PYTHONPATH

script:
- python -Wonce -u manage.py test -p '*_tests.py' -v 2
- cd ui/
- npm test

notifications:
  slack:
    secure: tYNwi4kff+8FWbv+nWqKZt28Qez0Dv77rJG6nvdiaO7QgPZmaiG5l8NqYdxV63CMgNzHwTFAz8ca9uOoh06o7+HuiFNNiqXEAu8umLvlnvkKT6itSDyImxxD7ypitUwcBEKkNy1fxhrLRPQVLjxz37885kA/VtWpm19A5vQ8A7w=

