DEPLOY_TO: 'gcloud-dev'
DEPLOY_TO_PREFIX: 'gcloud'

DOCKER_IMAGE_PREFIX: 'gcr.io/seqr-project'

# gcloud settings
CLUSTER_NAME: 'seqr-cluster-dev'
CLUSTER_MACHINE_TYPE: 'n1-highmem-2'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..
CLUSTER_NUM_NODES: 1

GCLOUD_PROJECT: 'seqr-project'
GCLOUD_ZONE: 'us-central1-b'

CLUSTER_EXTERNAL_IP: '104.198.135.79'
CLUSTER_HOSTNAME: 'seqr-dev.broadinstitute.org'

USE_EXTERNAL_POSTGRES_DB: false
#EXTERNAL_POSTGRES_IP: '35.185.45.141'
#SERVICE_ACCOUNT_KEY_FILE: 'account-key-file-30ea80400948.json'
