kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
    deployment: {{ DEPLOY_TO }}
spec:
  type: NodePort
  ports:
  - name: elasticsearch
    port: {{ ELASTICSEARCH_SERVICE_PORT }}
    nodePort: {{ ELASTICSEARCH_SERVICE_PORT }}
  selector:
    name: elasticsearch
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: elasticsearch
        deployment: {{ DEPLOY_TO }}
    spec:
      volumes:
      - name: elasticsearch-dbpath
        gcePersistentDisk:
          # This disk must already exist.
          pdName: {{ DEPLOY_TO }}-elasticsearch-disk
          fsType: ext4
      containers:
      - name: elasticsearch-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/elasticsearch:{{ TIMESTAMP }}
        ports:
        - containerPort: {{ ELASTICSEARCH_SERVICE_PORT }}
          protocol: TCP
        imagePullPolicy: Always
        volumeMounts:
        - name: elasticsearch-dbpath
          mountPath: /elasticsearch-data
        env:
        - name: ELASTICSEARCH_SERVICE_PORT
          value: "{{ ELASTICSEARCH_SERVICE_PORT }}"
      restartPolicy: Always
      dnsPolicy: ClusterFirst
