---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: seqr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: seqr
    spec:
      volumes:
      - name: seqr-code
        hostPath:
          path: {{ SEQR_REPO_PATH }}
      - name: data-dir
        # Kube-Solo mounts the persistent disk image onto the coreOS VM's /data directory
        hostPath:
          path: /data
      containers:
      - name: seqr-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/seqr
        ports:
        - containerPort: 8000
          protocol: TCP
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: seqr-code
          mountPath: /seqr
        - name: data-dir
          mountPath: /data
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres.password
        - name: OMIM_KEY
          valueFrom:
            secretKeyRef:
              name: seqr-secrets
              key: omim_key
        - name: POSTGRES_HOST
          value: postgres-svc
        - name: MONGO_HOST
          value: mongo-svc
        - name: PHENOTIPS_HOST
          value: phenotips-svc
        - name: MME_HOST
          value: matchbox-svc
      restartPolicy: Always
      dnsPolicy: ClusterFirst
