apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: seqr-frontend-config
  namespace: {{ NAMESPACE }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
