---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      volumes:
      - name: mongo-dbpath
        hostPath:
          path: {{ MONGO_DBPATH }}
      containers:
      - name: mongo-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: mongo-dbpath
          mountPath: /data/db
      restartPolicy: Always
      dnsPolicy: ClusterFirst
