kind: Service
apiVersion: v1
metadata:
  name: matchbox
spec:
  ports:
  - port: {{ MATCHBOX_SERVICE_PORT }}
  selector:
    name: matchbox
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: matchbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: matchbox
        deployment: {{ DEPLOY_TO }}
    spec:
      volumes:
      - name: matchbox-secrets-volume
        secret:
          secretName: matchbox-secrets
      containers:
      - name: matchbox-pod
        image: {{ DOCKER_IMAGE_PREFIX }}/matchbox:{{ TIMESTAMP }}
        ports:
        - containerPort: {{ MATCHBOX_SERVICE_PORT }}
          protocol: TCP
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "2"
        env:
        - name: MONGODB_DATABASE
          value: "mme_primary"
        - name: EXOMISER_DATA_DIR
          value: "/Exomiser/matchbox/data"
        - name: ALLOW_NO_GENE_IN_COMMON_MATCHES
          value: "false"
        - name: MONGO_SERVICE_HOSTNAME
          value: "mongo"
        volumeMounts:
        - name: matchbox-secrets-volume
          mountPath: /matchbox_deployment/config
          readOnly: true
      restartPolicy: Always
      dnsPolicy: ClusterFirst
