#####################################################
####### SETTINGS THAT MAY NEED TO BE MODIFIED #######

CLUSTER_NAME: 'seqr-cluster-dev'
CLUSTER_MACHINE_TYPE: 'n1-highmem-4'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..
CLUSTER_NUM_NODES: 1

CLUSTER_EXTERNAL_IP: '104.198.135.79'
CLUSTER_HOSTNAME: 'seqr-dev.broadinstitute.org'
BASE_URL: 'https://seqr-dev.broadinstitute.org/'

ELASTICSEARCH_SERVICE_EXTERNAL_IP: 10.20.0.18
ELASTICSEARCH_SERVICE_EXTERNAL_PORT: 9200
ELASTICSEARCH_VERSION: 7.8.1

KIBANA_SERVICE_HOSTNAME: kibana-kb-http

GCLOUD_PROJECT: 'seqr-project'
GCLOUD_ZONE: 'us-central1-b'

SEQR_GIT_BRANCH: 'master'

SEQR_POD_MEMORY_LIMIT: 15Gi
REDIS_POD_MEMORY_LIMIT: 8Gi

UPLOADED_PEDIGREE_FILE_RECIPIENTS: ''

KUBERNETES_VERSION: '1.16.13-gke.401'


###########################################################
####### SETTINGS THAT SHOULDN'T NEED TO BE MODIFIED #######

NAMESPACE: gcloud-dev

DEPLOY_TO: 'gcloud-dev'
DEPLOY_TO_PREFIX: 'gcloud'
DEPLOYMENT_TYPE: 'dev'
