DEPLOY_TO: 'minikube'
DEPLOY_TO_PREFIX: 'local'
DEPLOYMENT_TYPE: 'dev'

DOCKER_IMAGE_PREFIX: 'local/seqr'

USE_EXTERNAL_POSTGRES_DB: false

POSTGRES_DBPATH:  '/data/postgres'
MONGO_DBPATH:  '/data/mongo'
ELASTICSEARCH_DBPATH:  '/data/elasticsearch'

ELASTICSEARCH_JVM_MEMORY: 8g

CLUSTER_NAME: 'minikube'
CLOUD_PROVIDER: 'local'

# settings for making it easy to access gcloud resources from local pods
GCLOUD_PROJECT: ''
GCLOUD_ZONE: ''
GCLOUD_ELASTICSEARCH_CLUSTER_NAME: ''
