SEQR_VERSION: 0.1

GCLOUD_PROJECT: 'seqr-project'

DEPLOYMENT_TEMP_DIR: '/tmp'

COCKPIT_SERVICE_PORT: 9090
MATCHBOX_SERVICE_PORT: 9020
POSTGRES_SERVICE_PORT: 5432
ELASTICSEARCH_SERVICE_PORT: 30001
MONGO_SERVICE_PORT: 27017
KIBANA_SERVICE_PORT: 30002
PHENOTIPS_SERVICE_PORT: 8080
SEQR_SERVICE_PORT: 8000
SEQR_UI_DEV_PORT: 3000


MONGO_DISK_SIZE: '200Gb'
POSTGRES_DISK_SIZE: '200Gb'
ELASTICSEARCH_DISK_SIZE: '200Gb'
ELASTICSEARCH_SHARDED_DISK_SIZE: '1200Gb'
