name: Deploy

on:
  push:
    branches:
      - main
      - staging
      - reanalysis-dev

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      DOCKER_IMAGE: australia-southeast1-docker.pkg.dev/seqr-308602/seqr-project/seqr

    steps:
      - uses: actions/checkout@v4

      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: seqr-308602
          service_account_key: ${{ secrets.GCP_DEPLOY_KEY }}

      - name: gcloud docker auth
        run: |
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev

      - name: set deployment target
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo DEPLOY_TARGET=prod >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/staging' ]]; then
            echo DEPLOY_TARGET=staging >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/reanalysis-dev' ]]; then
            echo DEPLOY_TARGET=reanalysis-dev >> $GITHUB_ENV
          fi

      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: build UI
        run: |
          pushd ui
          npm install
          npm run build
          popd

      - name: build image
        run: |
          DOCKER_BUILDKIT=1
          docker build \
            --tag $DOCKER_IMAGE:${{ github.sha }} \
            --tag $DOCKER_IMAGE:gcloud-$DEPLOY_TARGET \
            -f deploy/docker/seqr/Dockerfile \
            .

      - name: push image
        run: docker push --all-tags $DOCKER_IMAGE

      - name: Update cloudrun jobs
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
        run: |
          # cloud run jobs to update
          run_job_names=("$DEPLOY_TARGET-schema-migrator" "$DEPLOY_TARGET-reference-schema-migrator" "$DEPLOY_TARGET-reference-updater" "$DEPLOY_TARGET-reference-update-hpo-terms" "$DEPLOY_TARGET-reference-import-panels")
          for cloud_run_target in "${run_job_names[@]}"; do

            gcloud beta run jobs update \
              "$cloud_run_target" \
              --region "australia-southeast1" \
              --image="$DOCKER_IMAGE:gcloud-$DEPLOY_TARGET"
          
          done;

      - name: restart seqr instances
        run: |
          gcloud compute instance-groups managed rolling-action replace \
            seqr-$DEPLOY_TARGET-group \
            --region australia-southeast1 \
            --max-unavailable 0 \
            --max-surge 3

      - name: apply schema
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
        run: |
          gcloud beta run jobs execute --wait \
            --region australia-southeast1 \
            $DEPLOY_TARGET-schema-migrator

          gcloud beta run jobs execute --wait \
            --region australia-southeast1 \
            $DEPLOY_TARGET-reference-schema-migrator
