name: Update seqr Version
on:
  push:
    branches:
      - seqr-helm-version
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update appVersion in the seqr HelmChart Chart.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'charts/seqr/Chart.yaml'
          propertyPath: 'appVersion'
          value: '1.0-toBeUpdated'  # todo: add seqr step ${{ steps.seqr.outputs.version }}
          repository: broadinstitute/seqr-helm
          masterBranchName: main
          branch: seqr-version-pr  # todo: update the branch name to something like deployment/${{ steps.image.outputs.version }}
          targetBranch: main
          createPR: true
          message: 'Update appVersion to #seqr-version#'  # todo: change #seqr-version# to ${{ steps.image.outputs.version }}'
          token: ${{ secrets.SEQR_VERSION_UPDATE_TOKEN }}
